const mockData = [
  {
    course: "CS 201",
    department: "CS",
    instructor: "Dr. Alice Johnson",
    finalExam: true,
    assignment: true,
    readingMaterial: true,
    contentRating: "A-",
    teachingRating: "B+",
    gradingRating: "B",
    workloadRating: "C+",
    syllabusLink: "https://example.com/cs201-syllabus.pdf",
    image: "https://example.com/images/cs201.jpg",
    instructorAvatar: "https://example.com/avatars/alice_johnson.jpg",
    tags: ["Programming", "Beginner", "CS101"],
    contentTopics: [
      "Week 1: Introduction to Programming",
      "Week 2: Object-Oriented Programming",
      "Week 3: Data Structures",
      "Week 4: Algorithm Analysis",
    ],
    reviews: [
      {
        content: "A great introduction to programming with detailed explanations.",
        teaching: "B+",
        grading: "B",
        workload: "C+",
      },
    ],
  },
  {
    course: "CS 204",
    department: "CS",
    instructor: "Prof. Robert White",
    finalExam: true,
    assignment: true,
    readingMaterial: true,
    contentRating: "B+",
    teachingRating: "B",
    gradingRating: "A-",
    workloadRating: "B-",
    syllabusLink: "https://example.com/cs204-syllabus.pdf",
    image: "https://example.com/images/cs204.jpg",
    instructorAvatar: "https://example.com/avatars/robert_white.jpg",
    tags: ["Software Development", "Web", "Databases"],
    contentTopics: [
      "Week 1: Software Development Life Cycle",
      "Week 2: Databases and SQL",
      "Week 3: Web Development Basics",
      "Week 4: Advanced Web Technologies",
    ],
    reviews: [
      {
        content: "Comprehensive course on software development. The projects were useful.",
        teaching: "B",
        grading: "A-",
        workload: "B-",
      },
    ],
  },
  {
    course: "CS 301",
    department: "CS",
    instructor: "Prof. John Smith",
    finalExam: true,
    assignment: true,
    readingMaterial: false,
    contentRating: "C+",
    teachingRating: "C",
    gradingRating: "B",
    workloadRating: "B-",
    syllabusLink: "https://example.com/cs301-syllabus.pdf",
    image: "https://example.com/images/cs301.jpg",
    instructorAvatar: "https://example.com/avatars/john_smith.jpg",
    tags: ["Data Structures", "Algorithms", "Advanced"],
    contentTopics: [
      "Week 1: Introduction to Data Structures",
      "Week 2: Sorting Algorithms",
      "Week 3: Graph Theory",
      "Week 4: Dynamic Programming",
    ],
    reviews: [
      {
        content: "The course lacked structure and was difficult to follow.",
        teaching: "C",
        grading: "B",
        workload: "B-",
      },
    ],
  }
];

export default mockData;
